### ISSUE TITLE
Respect disabled property before parsing CRON Expression

### ISSUE THREAD

**Issue by Alfagun74** [nestjs/schedule#1794]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to be able to disable the cron, by setting ``MY_INTERVAL_IN_MINS`` env var to `0` or lower using this code:

```ts
@Cron(`*/${Number(process.env.MY_INTERVAL_IN_MINS)} * * * *`, {
    disabled: Number(process.env.MY_INTERVAL_IN_MINS) <= 0,
  })
```
But it ends up erroring because it tries parsing the CRON with 0 minutes even though its disabled anyway.

```
error:   ┏ A fatal error occured +5ms
error:   ┃ [ 1] []
error:   ┃ [ 2] {
error:   ┃ [ 3]   context: undefined,
error:   ┃ [ 4]   error: CronError: Field (minute) has a step of zero
error:   ┃ [ 5]       at CronTime._parseField (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/time.js:408:27)
error:   ┃ [ 6]       at CronTime._parse (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/time.js:381:18)
error:   ┃ [ 7]       at new CronTime (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/time.js:37:18)
error:   ┃ [ 8]       at new CronJob (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/job.js:25:29)
error:   ┃ [ 9]       at Function.from (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/job.js:55:20)
error:   ┃ [10]       at /home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/@nestjs+schedule@4.1.1_@nestjs+common@10.4.6_class-transformer@0.5.1_class-validator@0.14.1_r_vq7ljdie4j2fbguhhtzbswecae/node_modules/@nestjs/schedule/dist/scheduler.orchestrator.js:56:44
error:   ┃ [11]       at Array.forEach (<anonymous>)
error:   ┃ [12]       at SchedulerOrchestrator.mountCron (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/@nestjs+schedule@4.1.1_@nestjs+common@10.4.6_class-transformer@0.5.1_class-validator@0.14.1_r_vq7ljdie4j2fbguhhtzbswecae/node_modules/@nestjs/schedule/dist/scheduler.orchestrator.js:54:18)
error:   ┃ [13]       at SchedulerOrchestrator.onApplicationBootstrap (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/@nestjs+schedule@4.1.1_@nestjs+common@10.4.6_class-transformer@0.5.1_class-validator@0.14.1_r_vq7ljdie4j2fbguhhtzbswecae/node_modules/@nestjs/schedule/dist/scheduler.orchestrator.js:27:14)
error:   ┃ [14]       at MapIterator.iteratee (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/@nestjs+core@10.4.6_@nestjs+common@10.4.6_class-transformer@0.5.1_class-validator@0.14.1_refl_fnmsffeipfaxcuvrctcpuvhsxa/node_modules/@nestjs/core/hooks/on-app-bootstrap.hook.js:22:43),
error:   ┃ [15]   timestamp: '2024-10-26T11:40:21.727Z'
error:   ┗ [16] }

/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/time.js:408
                    throw new errors_1.CronError(`Field (${unit}) has a step of zero`);
                          ^
Error: Field (minute) has a step of zero
    at CronTime._parseField (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/time.js:408:27)
    at CronTime._parse (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/time.js:381:18)
    at new CronTime (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/time.js:37:18)
    at new CronJob (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/job.js:25:29)
    at Function.from (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/cron@3.1.7/node_modules/cron/dist/job.js:55:20)
    at /home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/@nestjs+schedule@4.1.1_@nestjs+common@10.4.6_class-transformer@0.5.1_class-validator@0.14.1_r_vq7ljdie4j2fbguhhtzbswecae/node_modules/@nestjs/schedule/dist/scheduler.orchestrator.js:56:44
    at Array.forEach (<anonymous>)
    at SchedulerOrchestrator.mountCron (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/@nestjs+schedule@4.1.1_@nestjs+common@10.4.6_class-transformer@0.5.1_class-validator@0.14.1_r_vq7ljdie4j2fbguhhtzbswecae/node_modules/@nestjs/schedule/dist/scheduler.orchestrator.js:54:18)
    at SchedulerOrchestrator.onApplicationBootstrap (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/@nestjs+schedule@4.1.1_@nestjs+common@10.4.6_class-transformer@0.5.1_class-validator@0.14.1_r_vq7ljdie4j2fbguhhtzbswecae/node_modules/@nestjs/schedule/dist/scheduler.orchestrator.js:27:14)
    at MapIterator.iteratee (/home/alfagun74/git/phalcode/gamevault-backend/node_modules/.pnpm/@nestjs+core@10.4.6_@nestjs+common@10.4.6_class-transformer@0.5.1_class-validator@0.14.1_refl_fnmsffeipfaxcuvrctcpuvhsxa/node_modules/@nestjs/core/hooks/on-app-bootstrap.hook.js:22:43)
```

### Describe the solution you'd like

Just dont parse the CRON expression if it is disabled anyway.

For now i use a dirty hack i would prefer not to use:

```ts
@Cron(`*/${configuration.GAMES.INDEX_INTERVAL_IN_MINUTES > 0 ? configuration.GAMES.INDEX_INTERVAL_IN_MINUTES : 1} * * * *`, {
    disabled: configuration.GAMES.INDEX_INTERVAL_IN_MINUTES <= 0,
})
```

### What is the motivation / use case for changing the behavior?

Setting Cron minutes via env vars and disabling it by setting it to 0.

**Comment by sheerlox** [comment]
I don't think it makes much sense to update the library to not parse expressions for disabled jobs, especially since a disabled job might be dynamically enabled by calling the scheduler at runtime.

This issue is specific to your use case and arises from your design choices. Your hack specifically isn't that dirty, but here's what you might improve:

If you want to disable your job, instead of setting `INDEX_INTERVAL_IN_MINUTES` to `0` or a negative value, set it to `null` instead. This suggestion is motivated by multiple reasons:
- a `0` or negative minutes interval just does not exist conceptually (meaning the value is "illegal");
- it makes the purpose of setting that value clearer (disable job);
- it could also prevent silly mistakes in the future).

Then, you can adapt your job declaration as follows, which is a bit cleaner:
```ts
@Cron(`*/${configuration.GAMES.INDEX_INTERVAL_IN_MINUTES || 1} * * * *`, {
    disabled: configuration.GAMES.INDEX_INTERVAL_IN_MINUTES != null,
})
```
