### ISSUE TITLE
Type error in Timeout on Node 23

### ISSUE THREAD

**Issue by Eyon42** [nestjs/schedule#1833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When type checking in nestjs the following error shows up:
```
/node_modules/@nestjs/schedule/dist/decorators/timeout.decorator.js:12
    const [name, timeoutValue] = (0, util_1.isString)(nameOrTimeout)
                                                     ^

TypeError: (0 , util_1.isString) is not a function
```

The function isString from the module util was deprecated and removed on node version 23. The error does not appear when using previous versions where the function still exists.

### Minimum reproduction code

https://github.com/Eyon42/ISSUE-nest-schedule-isString

### Steps to reproduce

pnpm install
nvm install 23
nvm use 23
pnpm start

### Expected behavior

```
> schedule-issue@0.0.1 start <repo>
> nest start

<repo>/node_modules/.pnpm/@nestjs+schedule@4.1.1_@nestjs+common@10.4.13_reflect-metadata@0.2.2_rxjs@7.8.1__@nestjs+core@10.4.13/node_modules/@nestjs/schedule/dist/decorators/timeout.decorator.js:12
    const [name, timeoutValue] = (0, util_1.isString)(nameOrTimeout)
                                                     ^

TypeError: (0 , util_1.isString) is not a function
    at Timeout (<repo>/node_modules/.pnpm/@nestjs+schedule@4.1.1_@nestjs+common@10.4.13_reflect-metadata@0.2.2_rxjs@7.8.1__@nestjs+core@10.4.13/node_modules/@nestjs/schedule/dist/decorators/timeout.decorator.js:12:54)
    at Object.<anonymous> (<repo>src/app.service.ts:6:11)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1698:10)
    at Module.load (node:internal/modules/cjs/loader:1303:32)
    at Function._load (node:internal/modules/cjs/loader:1117:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1325:12)
    at require (node:internal/modules/helpers:136:16)

Node.js v23.3.0
 ELIFECYCLE  Command failed with exit code 1.
```

### Package version

4.1.1

### NestJS version

10.0.0

### Node.js version

23.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR, replacing the use of this util with a regular `typeof === 'string'`?
